name: Publish 'latest' image

on:
  release:
    types:
      - "created"

jobs:
  cd:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-release.yml@main
    with:
      service-name: worlds-content-server
      dockerfile-url: https://raw.githubusercontent.com/decentraland/platform-actions/main/Dockerfile.alpine
    secrets: inherit
