name: CI/CD on main branch

on:
  push:
    branches:
      - "main"

jobs:
  cd:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: worlds-content-server
      dockerfile-url: https://raw.githubusercontent.com/decentraland/platform-actions/main/Dockerfile.alpine
      deployment-environment: dev
    secrets: inherit
